# Generated by Django 5.1.1 on 2025-10-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='page_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
