# Generated by Django 5.1.1 on 2024-09-30 08:25

import django.db.models.deletion
import django_ckeditor_5.fields
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('uid', models.CharField(max_length=255)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[420, 420], upload_to='shop/category/images')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='ЧПУ')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('html_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='SEO текст')),
                ('items_count', models.IntegerField(default=0, null=True, verbose_name='Кол-во товаров')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('order_num',),
            },
        ),
        migrations.CreateModel(
            name='Coating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='ЧПУ')),
            ],
            options={
                'verbose_name': 'Вставка',
                'verbose_name_plural': 'Вставки',
            },
        ),
        migrations.CreateModel(
            name='Fineness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='ЧПУ')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('article', models.CharField(blank=True, max_length=20, null=True, verbose_name='Артикул')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='В наличии?')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[800, 600], upload_to='shop/product/images')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, help_text='Если не заполнено, создается на основе поля Назавание', max_length=255, null=True, verbose_name='ЧПУ')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание')),
                ('coating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.coating')),
                ('fineness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.fineness')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Размер')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Остаток')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена')),
                ('price_opt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена оптовая')),
                ('min_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Минимальный вес')),
                ('max_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Максимальный вес')),
                ('avg_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Средний вес')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='shop.product')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('uid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='ЧПУ')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[420, 420], upload_to='shop/category/images')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('html_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='SEO текст')),
                ('items_count', models.IntegerField(default=0, null=True, verbose_name='Кол-во товаров')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='shop.category')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ('order_num',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.subcategory'),
        ),
    ]
