# Generated by Django 5.1.1 on 2024-09-30 17:41

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_sizefilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='selected_amount',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[420, 420], upload_to='shop/category/images'),
        ),
    ]
