# Generated by Django 5.1.1 on 2024-10-05 17:24

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_size_selected_amount_alter_subcategory_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coating',
            options={'verbose_name': 'Покрытие', 'verbose_name_plural': 'Покрытия'},
        ),
        migrations.AlterModelOptions(
            name='fineness',
            options={'verbose_name': 'Вставка', 'verbose_name_plural': 'Вставки'},
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[20, 20], upload_to='shop/category/icon'),
        ),
        migrations.AlterField(
            model_name='product',
            name='coating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Покрытие', to='shop.coating'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fineness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Вставка', to='shop.fineness'),
        ),
    ]
