# Generated by Django 5.1.1 on 2024-10-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_coating_options_alter_fineness_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coating',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='coating',
            old_name='slug',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='fineness',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='fineness',
            old_name='slug',
            new_name='value',
        ),
    ]
