# Generated by Django 5.1.1 on 2024-10-15 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_material_metal_material_probe'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Фильтр', to='shop.subcategoryfilter'),
        ),
    ]
