# Generated by Django 5.1.1 on 2024-10-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='size',
            name='price_opt',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена оптовая'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='sizefilter',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Размер'),
        ),
    ]
