# Generated by Django 5.1.1 on 2024-10-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_category_is_active_subcategory_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizefilter',
            options={'ordering': ('order_num',)},
        ),
        migrations.AddField(
            model_name='sizefilter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Отображать?'),
        ),
        migrations.AddField(
            model_name='sizefilter',
            name='order_num',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
