# Generated by Django 5.1.1 on 2024-10-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_sizefilter_options_sizefilter_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='coatings',
            field=models.ManyToManyField(blank=True, null=True, to='shop.coating'),
        ),
        migrations.AddField(
            model_name='category',
            name='materials',
            field=models.ManyToManyField(blank=True, null=True, to='shop.material'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Размер'),
        ),
    ]
