# Generated by Django 5.1.1 on 2024-10-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_category_coatings_category_materials_alter_size_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('uid', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Популярные товары',
                'verbose_name_plural': 'Популярные товары',
                'ordering': ('order_num',),
            },
        ),
    ]
