# Generated by Django 5.1.1 on 2024-11-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_product_options_product_not_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул'),
        ),
    ]
