# Generated by Django 5.1.1 on 2025-01-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_product_options_product_items_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hidden_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='null_opt_price',
            field=models.BooleanField(default=False),
        ),
    ]
