# Generated by Django 5.1.1 on 2025-02-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_product_hidden_category_product_null_opt_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_lower',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
