# Generated by Django 5.1.1 on 2025-02-25 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_product_name_lower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ('-size',), 'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='shop/product/images_fixed')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
        ),
    ]
