# Generated by Django 5.1.1 on 2025-02-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_size_options_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ('size',), 'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AddField(
            model_name='image',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
