# Generated by Django 5.1.1 on 2025-02-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_size_options_image_is_main'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductImage',
        ),
    ]
