# Generated by Django 5.1.1 on 2025-04-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_fineness_label_lower_product_article_lower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_garniture',
            field=models.BooleanField(default=False),
        ),
    ]
