# Generated by Django 5.1.1 on 2025-04-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_product_has_garniture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
