# Generated by Django 5.1.1 on 2025-04-23 06:55

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_product_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=10)),
                ('image', models.FileField(blank=True, null=True, upload_to='shop/promo/')),
                ('col_span', models.IntegerField(default=12)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['order_num'],
            },
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Открывать по-умолчанию?'),
        ),
        migrations.CreateModel(
            name='PromoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.promo')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategorySizeFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True, verbose_name='Размер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_filters', to='shop.subcategory')),
            ],
            options={
                'ordering': ('order_num',),
            },
        ),
    ]
