# Generated by Django 5.1.1 on 2025-04-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_promo_subcategory_is_default_promoitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='Распродажа'),
        ),
    ]
