# Generated by Django 5.1.1 on 2025-05-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='price_init',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Цена исходная'),
        ),
        migrations.AddField(
            model_name='size',
            name='price_opt_init',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Цена оптовая исходная'),
        ),
    ]
