# Generated by Django 5.1.1 on 2025-08-26 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_alter_product_has_garniture_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectionitem',
            name='uid',
        ),
        migrations.AddField(
            model_name='selectionitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
