# Generated by Django 5.1.1 on 2025-09-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_remove_selectionitem_uid_selectionitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='size',
            name='price_init',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена исходная'),
        ),
        migrations.AlterField(
            model_name='size',
            name='price_opt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена оптовая'),
        ),
        migrations.AlterField(
            model_name='size',
            name='price_opt_init',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена оптовая исходная'),
        ),
    ]
