# Generated by Django 5.1.1 on 2025-10-08 05:43

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_size_price_alter_size_price_init_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Камень',
                'verbose_name_plural': 'Камень',
            },
        ),
        migrations.AlterField(
            model_name='selection',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=99, scale=None, size=[900, 600], upload_to='banner/images', verbose_name='Картинка 670х450'),
        ),
        migrations.CreateModel(
            name='FinenessGem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('fineness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gems', to='shop.fineness')),
                ('gem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.gem')),
            ],
            options={
                'verbose_name': 'Элементы вставки',
                'verbose_name_plural': 'Элементы вставки',
            },
        ),
        migrations.CreateModel(
            name='GemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('gems', models.ManyToManyField(to='shop.gem')),
            ],
            options={
                'verbose_name': 'Группа камней',
                'verbose_name_plural': 'Группа камней',
            },
        ),
    ]
