# Generated by Django 5.1.1 on 2025-10-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_gem_alter_selection_image_finenessgem_gemgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='finenessgem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='finenessgem',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
