# Generated by Django 5.1.1 on 2025-10-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_finenessgem_quantity_finenessgem_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finenessgem',
            name='uid',
        ),
    ]
