# Generated by Django 5.1.1 on 2025-10-29 05:58

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_remove_finenessgem_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text="Уникальный путь страницы (например: 'about' или 'contacts')", max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='SEO текст')),
            ],
            options={
                'verbose_name': 'SEO для страницы',
                'verbose_name_plural': 'SEO страницы',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='page_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='page_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
