# Generated by Django 5.1.1 on 2025-12-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_seopage_product_page_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='shop/files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Файл выгрузки',
                'verbose_name_plural': 'Файлы выгрузки',
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='use_white_text',
            field=models.BooleanField(default=False, verbose_name='Белый текст'),
        ),
    ]
