# Generated by Django 5.1.1 on 2025-12-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_itemsfile_banner_use_white_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='use_small_text',
            field=models.BooleanField(default=False, verbose_name='Маленький текст'),
        ),
    ]
