# Generated by Django 5.1.1 on 2026-01-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_category_page_description_category_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoryfilter',
            name='page_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='subcategoryfilter',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
