# Generated by Django 5.1.1 on 2026-01-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_subcategoryfilter_page_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoryfilter',
            name='page_description',
        ),
        migrations.RemoveField(
            model_name='subcategoryfilter',
            name='page_title',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='page_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
