# Generated by Django 5.1.1 on 2024-10-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_avatar_remove_user_uuid_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_opt_user',
            field=models.BooleanField(default=False, verbose_name='Оптовый'),
        ),
    ]
