# Generated by Django 5.1.1 on 2025-01-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_callbackform'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activate_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
