# Generated by Django 5.1.1 on 2024-10-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_price_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Создан'),
        ),
    ]
