# Generated by Django 5.1.1 on 2024-10-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='article',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='avg_weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Средний вес'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.FileField(null=True, upload_to='order/images'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
