# Generated by Django 5.1.1 on 2025-01-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_status_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статус'},
        ),
    ]
