# Generated by Django 5.1.1 on 2025-05-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_status_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Размер'),
        ),
    ]
