# Generated by Django 5.1.1 on 2025-06-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='order/images'),
        ),
    ]
