# Generated by Django 5.1.1 on 2025-10-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_orderitem_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
