# Generated by Django 5.1.1 on 2025-12-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_decline',
            field=models.BooleanField(default=False, verbose_name='Отказ'),
        ),
    ]
